import type {Pose} from './kaomojiGeometry';
import {handPath,oval} from './kaomojiGeometry';
export function artAttributes(p:Pose):Record<string,Record<string,string>>{
 const transform=`translate(${p.bodyX} ${p.bodyY}) rotate(${p.angle} 100 82) translate(100 82) scale(${1+p.breath} ${1-p.breath*.5}) translate(-100 -82)`;
 return {
  body:{transform},gaze:{transform:`translate(${p.gazeX} ${p.gazeY})`},'eye-l':{d:oval(88,87,2.8,3.1*p.blink),opacity:String(1-p.smile)},'eye-r':{d:oval(112,87,2.8,3.1*p.blink),opacity:String(1-p.smile)},smile:{opacity:String(p.smile)},
  'hand-l':{d:handPath(52+p.bodyX,96+p.bodyY,p.leftX,p.leftY)},'hand-r':{d:handPath(148+p.bodyX,96+p.bodyY,p.rightX,p.rightY)},'hand-l-outline':{d:handPath(52+p.bodyX,96+p.bodyY,p.leftX,p.leftY).slice(0,-1)},'hand-r-outline':{d:handPath(148+p.bodyX,96+p.bodyY,p.rightX,p.rightY).slice(0,-1)},
  film:{opacity:String(p.film),transform:`translate(${p.filmX} ${p.filmY})`},'film-window':{width:String(p.filmW-4),height:String(p.filmH-4)},'film-bg':{width:String(p.filmW),height:String(p.filmH)},'film-cells':{transform:`translate(${p.filmOffset} 0)`},handles:{opacity:String(p.handles)},'handle-l':{x:String(p.handleL-p.filmX-3.5)},'handle-r':{x:String(p.handleR-p.filmX-3.5)},range:{x:String(p.handleL-p.filmX),width:String(Math.max(1,p.handleR-p.handleL))},
  source:{opacity:String(p.source)},stack:{opacity:String(p.stack),transform:`translate(${p.stackX} ${p.stackY})`},'stack-front':{width:String(p.stackW),height:String(p.stackH)},'stack-back':{width:String(p.stackW),height:String(p.stackH),opacity:String(p.stackBack)},stamp:{opacity:String(p.stamp)},card:{opacity:String(p.card),transform:`translate(${p.cardX-19*p.cardScale} ${p.cardY-12*p.cardScale}) scale(${p.cardScale}) rotate(${p.cardAngle} 19 12)`},'left-stack':{opacity:String(p.leftStack)},tag:{opacity:String(p.tag),transform:`translate(${p.tagX-10} ${p.tagY-8})`},bookmark:{opacity:String(p.bookmark)}
 };
}
export default function KaomojiArt({pose}:{pose:Pose}){const a=artAttributes(pose);return <g className="kaomoji-art">
 <g data-art="body" {...a.body}><path className="kao-body" d="M49 96 C46 70 65 51 94 50 C125 47 150 68 150 97 C150 124 130 138 100 138 C70 138 49 123 49 96Z"/><g data-art="gaze" {...a.gaze}><path data-art="eye-l" className="kao-eye" {...a['eye-l']}/><path data-art="eye-r" className="kao-eye" {...a['eye-r']}/><path data-art="smile" className="kao-face" d="M84 88 Q88 82 92 88 M108 88 Q112 82 116 88" {...a.smile}/><path className="kao-face kao-mouth" d="M93 93 C92 99 99 101 100 96 C101 101 108 99 107 93"/><path className="kao-cheek" d={oval(79,94,6,3)+oval(121,94,6,3)}/></g></g>
 <g data-art="film" {...a.film}><rect data-art="film-bg" className="kao-card" x="0" y="0" rx="7" {...a['film-bg']}/><svg x="2" y="2" width={pose.filmW-4} height={pose.filmH-4} overflow="hidden" data-art="film-window"><g data-art="film-cells" {...a['film-cells']}>{[0,1,2,3,4,5].map(i=><rect key={i} className="kao-detail" x={7+i*19} y="2" width="12" height="9" rx="1.5"/>)}</g></svg><g data-art="handles" {...a.handles}><rect data-art="range" className="kao-range" y="1" height="15" {...a.range}/><rect data-art="handle-l" className="kao-handle" y="-3" width="7" height="23" rx="3.5" {...a['handle-l']}/><rect data-art="handle-r" className="kao-handle" y="-3" width="7" height="23" rx="3.5" {...a['handle-r']}/></g></g>
 <g data-art="source" {...a.source}><rect className="kao-card" x="22" y="111" width="47" height="18" rx="5"/><path className="kao-detail" d="M32 117V123 M43 117V123 M54 117V123"/></g>
 <g data-art="left-stack" {...a['left-stack']}><rect className="kao-card" x="33" y="112" width="44" height="25" rx="5"/></g>
 <g data-art="stack" {...a.stack}><rect data-art="stack-back" className="kao-card" x="4" y="5" rx="5" {...a['stack-back']}/><rect data-art="stack-front" className="kao-card" x="0" y="0" rx="5" {...a['stack-front']}/><path data-art="stamp" className="kao-detail" d="M19 15 L26 21 L38 9" {...a.stamp}/></g>
 <g data-art="card" {...a.card}><rect className="kao-card" width="38" height="24" rx="4"/><path className="kao-detail" d="M9 7H28 M9 16H22"/></g>
 <g data-art="tag" {...a.tag}><rect className="kao-card" width="20" height="16" rx="3"/><path className="kao-detail" d="M5 6H15 M5 11H12"/></g><g data-art="bookmark" {...a.bookmark}><path className="kao-bookmark" d="M98 110 Q98 107 101 107 H104 Q107 107 107 110 V133 L102.5 129 L98 133Z"/></g>
 <path data-art="hand-l" className="kao-hand" {...a['hand-l']}/><path data-art="hand-l-outline" className="kao-hand-outline" {...a['hand-l-outline']}/><path data-art="hand-r" className="kao-hand" {...a['hand-r']}/><path data-art="hand-r-outline" className="kao-hand-outline" {...a['hand-r-outline']}/>
 </g>;}
