import React from 'react';
import {createRoot} from 'react-dom/client';
import App from './App';
import './style.css';
import './blanca.css';
import './clipDetails.css';
import './updates.css';
import './player.css';
import './v3.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
