import {useEffect,useMemo,useRef,useState} from 'react';
import {Play,Pause,Volume2,VolumeX,Maximize,RotateCcw,X} from 'lucide-react';
import type {Clip} from './shared';
import {ApexIcon} from './ClipDetails';
import InfoTip from './InfoTip';
import {clipEvents,eventGroups,eventIcon,eventLabel,type ClipEvent} from './eventTimeline';
export function preciseClock(seconds:number){const n=Math.round(Math.max(0,seconds)*100),s=Math.floor(n/100),m=Math.floor(s/60),h=Math.floor(m/60);return(h?String(h).padStart(2,'0')+':':'')+String(m%60).padStart(2,'0')+':'+String(s%60).padStart(2,'0')+'.'+String(n%100).padStart(2,'0');}
export default function PlayerControls({clip,video,stage,onError,onCollapse,onDetails}:{clip:Clip;video:{current:HTMLVideoElement|null};stage:{current:HTMLDivElement|null};onError:(message:string)=>void;onCollapse:()=>void;onDetails:()=>void}){
 const [time,setTime]=useState(0),[duration,setDuration]=useState(clip.duration),[playing,setPlaying]=useState(false),[volume,setVolume]=useState(1),[muted,setMuted]=useState(false),[width,setWidth]=useState(600),[group,setGroup]=useState<string|null>(null),[selected,setSelected]=useState<ClipEvent|null>(null);const bar=useRef<HTMLDivElement>(null),pending=useRef<number|null>(null);
 useEffect(()=>{const v=video.current;if(!v)return;const update=()=>{setTime(v.currentTime);setPlaying(!v.paused&&!v.ended);setMuted(v.muted);setVolume(v.volume);if(Number.isFinite(v.duration)&&v.duration>0)setDuration(v.duration);};const ready=()=>{if(pending.current!==null){v.currentTime=pending.current;pending.current=null;}update();};for(const name of ['timeupdate','play','pause','volumechange','ended','seeked'])v.addEventListener(name,update);v.addEventListener('loadedmetadata',ready);update();return()=>{for(const name of ['timeupdate','play','pause','volumechange','ended','seeked'])v.removeEventListener(name,update);v.removeEventListener('loadedmetadata',ready);};},[clip.path,video]);
 useEffect(()=>{if(!bar.current)return;const observer=new ResizeObserver(entries=>setWidth(entries[0].contentRect.width));observer.observe(bar.current);return()=>observer.disconnect();},[]);
 const events=useMemo(()=>clipEvents(clip,duration),[clip,duration]),groups=useMemo(()=>eventGroups(events,duration,width),[events,duration,width]);
 function seek(target:number){const v=video.current;if(!v)return;const next=Math.max(0,Math.min(duration,target));v.dataset.seekRequested=String(next);if(v.readyState<1)pending.current=next;else v.currentTime=next;setTime(next);}
 function choose(event:ClipEvent){seek(event.clipTime);setSelected(event);setGroup(null);}
 function play(){const v=video.current;if(!v)return;if(v.paused)void v.play().catch(()=>onError('无法开始播放，可重试或使用系统播放器'));else v.pause();}
 return <div className="player-controls">
  {selected&&<div className="event-hud" role="status" data-event-kind={selected.kind}><ApexIcon file={'stats/'+eventIcon(selected.kind)+'.svg'}/><b>{eventLabel(selected.kind)}</b><time>{preciseClock(selected.clipTime)}</time>{(selected.text||selected.confidence!==undefined)&&<InfoTip label="查看此事件证据" text={(selected.text||'')+(Number.isFinite(selected.confidence)?' · 识别置信度 '+Math.round(selected.confidence!*100)+'%':'')}/>}<button aria-label="回放此事件" onClick={()=>{seek(selected.clipTime);void video.current?.play().catch(()=>onError('无法回放此事件'));}}><RotateCcw size={14}/></button><button aria-label="关闭事件信息" onClick={()=>setSelected(null)}><X size={14}/></button></div>}
  <div className="event-seekbar" ref={bar}>
   <div className="event-markers">{groups.map(g=><div key={g.id} className="event-marker-slot" style={{left:Math.max(2,Math.min(98,g.fraction*100))+'%'}}><button data-fixed-ink className={'event-marker '+(g.events.some(e=>e.id===selected?.id)?'chosen':'')} aria-label={g.events.length===1?eventLabel(g.events[0].kind)+' '+preciseClock(g.events[0].clipTime):'展开 '+g.events.length+' 个密集事件'} aria-expanded={g.events.length>1?group===g.id:undefined} onClick={()=>g.events.length===1?choose(g.events[0]):setGroup(group===g.id?null:g.id)}><ApexIcon file={'stats/'+eventIcon(g.events[0].kind)+'.svg'}/>{g.events.length>1&&<span>{g.events.length}</span>}</button>
    {group===g.id&&<div className="event-group" role="group" aria-label="密集事件"><button className="event-group-close" aria-label="关闭事件组" onClick={()=>setGroup(null)}><X size={14}/></button>{g.events.map(e=><button key={e.id} aria-label={'跳转 '+eventLabel(e.kind)+' '+preciseClock(e.clipTime)} onClick={()=>choose(e)}><ApexIcon file={'stats/'+eventIcon(e.kind)+'.svg'}/><span>{eventLabel(e.kind)}</span><time>{preciseClock(e.clipTime)}</time></button>)}</div>}
   </div>)}</div>
   <input type="range" className="video-seek" aria-label="视频进度" min="0" max={duration||0} step="0.01" value={Math.min(time,duration)} onChange={e=>seek(e.target.valueAsNumber)} style={{background:'linear-gradient(to right,var(--card-accent) '+(duration>0?time/duration*100:0)+'%,var(--card-line) 0)'}}/>
  </div>
  <div className="player-control-row"><button className="player-play" aria-label={playing?'暂停视频':'播放视频'} onClick={play}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><time>{preciseClock(time)} / {preciseClock(duration)}</time><InfoTip label="事件标记说明" text={events.length?'事件时刻来自本人提示，按实际关键帧对齐起点换算。密集节点可展开逐条跳转；没有事件级武器或目标字段时不推测。':'此片段没有可靠的事件级证据；未识别不等于0，不用整段枪械列表冒充单次击杀信息。'}/><button className="player-details-button" aria-label="片段详情" onClick={onDetails}>详情</button><button className="player-collapse-button" aria-label="收起播放" onClick={onCollapse}>收起</button><div className="player-volume"><button aria-label={muted?'取消静音':'静音'} onClick={()=>{if(video.current)video.current.muted=!video.current.muted;}}>{muted||volume===0?<VolumeX size={17}/>:<Volume2 size={17}/>}</button><input type="range" aria-label="音量" min="0" max="1" step="0.01" value={muted?0:volume} onChange={e=>{if(video.current){video.current.volume=e.target.valueAsNumber;video.current.muted=false;}}}/></div><button aria-label="切换全屏" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void stage.current?.requestFullscreen().catch(()=>onError('无法进入全屏'));}}><Maximize size={17}/></button></div>
 </div>;
}
