const{test}=require('node:test');const assert=require('node:assert/strict');const{poseAt,staticPose,blendPose,handPath,handContour}=require('../dist-electron/src/kaomojiGeometry');
test('二分把手三次收拢，手端持续接触把手',()=>{const first=poseAt('bisect',.2),last=poseAt('bisect',2.7);assert.ok(last.handleR-last.handleL<first.handleR-first.handleL);for(let t=0;t<3.6;t+=.05){const p=poseAt('bisect',t);assert.equal(p.leftX,p.handleL);assert.equal(p.rightX,p.handleR);}});
test('导出先左手取片、再右手摆片，抓握位置与卡片绑定',()=>{for(let t=0;t<4.2*.28;t+=.05){const p=poseAt('export',t);assert.equal(p.leftX,p.cardX-17);assert.equal(p.leftY,p.cardY+10);}for(let t=4.2*.48;t<4.2*.74;t+=.05){const p=poseAt('export',t);assert.equal(p.rightX,p.cardX+17);assert.equal(p.rightY,p.cardY+10);}});
test('完成只点头一次且一秒后保持安静',()=>{assert.deepEqual(poseAt('completed',1.1),poseAt('completed',9));assert.equal(poseAt('completed',2).smile,1);});
test('辅助阶段拥有工作姿态而非 idle 占位',()=>{for(const s of['importing','probe','fine','numeric','lifecycle','outcomes','weapons','audit','verify','stopping','error'])assert.notDeepEqual(staticPose(s),staticPose('idle'));});
test('550ms 结束连续转场保留精确目标，零时刻保留当前状态',()=>{const a=poseAt('export',1),b=poseAt('coarse',1);assert.deepEqual(blendPose(a,b,0,0),a);assert.deepEqual(blendPose(a,b,1,550),b);});
test('手填充闭合但描边省去根部封口',()=>{const d=handPath(52,96,88,118);assert.ok(d.endsWith('Z'));assert.ok(!d.slice(0,-1).endsWith('Z'));});
test('指定外伸时点保持12px厚度，轮廓无自交',()=>{const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);const intersects=(a,b,c,d)=>cross(a,b,c)*cross(a,b,d)<-1e-7&&cross(c,d,a)*cross(c,d,b)<-1e-7;
 for(const [stage,t]of[['importing',0],['importing',2.67],['export',0],['export',4.08],['verify',0],['verify',3.83]]){const p=poseAt(stage,t);for(const [x,gx,gy]of[[52+p.bodyX,p.leftX,p.leftY],[148+p.bodyX,p.rightX,p.rightY]]){const g=handContour(x,96+p.bodyY,gx,gy);g.outer.forEach((point,i)=>assert.ok(Math.abs(Math.hypot(point[0]-g.inner[i][0],point[1]-g.inner[i][1])-12)<1e-6));const v=g.points;for(let i=0;i<v.length;i++)for(let j=i+2;j<v.length;j++){if(i===0&&j===v.length-1)continue;assert.ok(!intersects(v[i],v[(i+1)%v.length],v[j],v[(j+1)%v.length]),`${stage} ${t}`);}}}
});
test('手掌横向经过根部时弯曲侧连续，不触发阈值跳变',()=>{let previous=null;for(let gx=143.5;gx<=144.6;gx+=.005){const points=handContour(144,96,gx,125).points;if(previous){const delta=Math.max(...points.map((p,i)=>Math.hypot(p[0]-previous[i][0],p[1]-previous[i][1])));assert.ok(delta<.025,String(delta));}previous=points;}});
